#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
i=0
while [ $i -lt 11 ];
do 
    if [ $i -eq 9 ]; 
    then
        echo "Hi"
        (( i++ ))
    else
        echo "Holberton School"
        (( i++ ))
    fi    
done

