#!/usr/bin/env bash
#bad luck in 4, good luck in 8
i=1
while [ $i -lt 11 ]; 
do
    if [ $i -eq 4 ]
      then
	echo "bad luck"
      elif [ $i -eq 8 ]
      then
	echo "good luck"
      else
	echo "Holberton School"
      fi
      (( i++ ))
done
