#!/usr/bin/env bash
#check file exist
a="$(pwd)/holbertonschool"
if [ -e "$a" ]
then
    echo "holbertonschool file exists"
    if [ -s "$a" ]
    then
	echo "holbertonschool file is not empty"
    else
	echo "holbertonschool file is empty"
    fi
    if [ -f "$a" ]
    then
	echo "holbertonschool is a regular file"
    fi
else
    echo "holbertonschool file does not exist"
fi
